'use strict';
const E=WorkflowEngine,$=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const names={A:'純子球挑戰',B:'固定球位單桿挑戰',C:'球位輪換挑戰',D:'單局清檯挑戰',E:'兩桿做球清檯'};
const pocketNames={top_left:'左上袋',top_right:'右上袋',bottom_left:'左下袋',bottom_right:'右下袋',top_center:'上中袋',bottom_center:'下中袋'};
let runtime=null,levels=[],selected=0,importText='',lastError='',showGiveup=false;
try{levels=COACH_PRESETS.map(p=>({number:p.id,spec:CoachModel.toSpec(CoachModel.fromLegacy(p))}));}catch(e){lastError=e.message;}
const steps=['模板與球桌標記','請擺球・確認位置','開始擊球','逐桿判定','續桿／重擺','結算'];
const stages={template:0,placement:1,ready:2,moving:2,judging:3,result:4,continuation:4,settlement:5};
function button(label,fn,primary=false){const b=document.createElement('button');b.textContent=label;b.className=primary?'primary':'';b.onclick=()=>{try{lastError='';fn();render()}catch(e){lastError=e.message;$('error').textContent=lastError}};$('actions').append(b);}
function summary(s){const t=s.flow.template;return `<h3>${esc(s.name)}</h3><p class="teaching">${esc(s.teaching)}</p><div class="stats"><div>總${s.scoring.unit==='balls'?'球數':'次數'} <b>${s.scoring.total}</b></div><div>過關 <b>${s.scoring.pass}</b></div><div>星等 <b>${s.scoring.stars.join(' / ')}</b></div></div><p>${esc(names[t])} · ${s.objectRules.order==='ascending'?'按號碼由小到大':'任意順序'}</p>`;}
function ruleText(q,side){const n={pocket:'進入指定袋口',zone:'停進目標區域',stay:'留在桌面',pocket_or_zone:'進指定袋口或停進目標區域',none:'不使用'};return `<div class="rule"><b>${side}</b>：${n[q.target]}${q.pockets.length?'（'+q.pockets.map(p=>pocketNames[p]).join('、')+'）':''}${q.lineRequirement.required?`<br>本桿必須接觸線段 ${q.lineRequirement.lineIndexes.map(i=>i+1).join('、')}`:''}</div>`;}
function table(r,initial=false){const s=r.spec,balls=initial?s.setup.balls:r.active,q=E.rules(r),shot=r.shot,fracX=x=>(.0543+x/8*.891)*800,fracY=y=>(.0979+y/4*.8035)*440;
 const shapes=[...s.diagram.zones.map(z=>({...z,kind:'zone'})),...s.diagram.lines.map(z=>({...z,kind:'line'}))].filter(z=>(s.flow.template!=='E'||z.shot==null||z.shot===shot)&&(z.kind!=='zone'||['zone','pocket_or_zone'].includes(z.side==='cue'?q.cue.target:q.object.target))).map(z=>z.kind==='zone'?`<rect x="${Math.min(z.x1,z.x2)*800}" y="${Math.min(z.y1,z.y2)*440}" width="${Math.abs(z.x2-z.x1)*800}" height="${Math.abs(z.y2-z.y1)*440}" fill="${z.side==='cue'?'#78cbee':'#ffdc67'}" opacity=".4"/>`:`<line x1="${z.x1*800}" y1="${z.y1*440}" x2="${z.x2*800}" y2="${z.y2*440}" stroke="${z.side==='cue'?'#78cbee':'#ffdc67'}" stroke-width="5"/>`).join('');
 const colors=['#efc346','#3273bf','#c75040','#8853a4','#ef903a','#40886a','#874c3f'];
 return `<svg viewBox="0 0 800 440" role="img" aria-label="球桌與當前球位"><image href="../level_engine/assets/table.png" width="800" height="440"/>${shapes}${balls.map((b,i)=>`<circle cx="${fracX(b.x)}" cy="${fracY(b.y)}" r="12" fill="${b.id==='cue'?'#fff':b.id==='gray'?'#aaa':b.id==='red'?'#e54d46':colors[(Number(b.id)-1)%7]||'#222'}" stroke="#ffffff90" stroke-width="2"/><text x="${fracX(b.x)}" y="${fracY(b.y)+4}" fill="${b.id==='cue'?'#555':'#fff'}" text-anchor="middle" font-size="12" font-weight="bold">${esc(b.id==='cue'?'母':b.id)}</text>`).join('')}</svg><p class="hint">黃色：子球目標　藍色：母球目標 · 桿次 ${shot}</p>`;}
function load(text){const raw=JSON.parse(text);const list=Array.isArray(raw)?raw:Array.isArray(raw.levels)?raw.levels:[raw];const checked=list.map(s=>E.load(s));if(checked.length>1){levels=checked.map((spec,i)=>({number:i+1,spec}));selected=0;}runtime=E.create(checked[0]);}
function render(){const r=runtime,index=r?stages[r.phase]:0;$('flow').innerHTML=steps.map((s,i)=>`<li class="${i===index?'active':i<index?'done':''}" ${i===index?'aria-current="step"':''}>${s}</li>`).join('');$('template').textContent=r?`${r.spec.flow.template} · ${names[r.spec.flow.template]}`:'等待載入';$('screen-title').textContent=r?steps[index]:'選擇關卡';$('counter').textContent=r?`得分 ${r.score} · ${r.spec.scoring.unit==='balls'?'第 '+r.shot+' 桿':'第 '+Math.min(r.attempt+1,r.spec.scoring.total)+' / '+r.spec.scoring.total+' 次'}`:'';$('actions').replaceChildren();$('error').textContent=lastError;
 $('branch').textContent=r?({A:r.spec.scoring.unit==='balls'?'開局擺好全部子球，按號碼直接擊打；成功接下一顆，不重擺；任一顆失敗即結束。':'每次只擺一顆子球；判定後進入下一次。',B:'每桿判定後，母球與子球都回到初始球位。',C:'直接使用 rounds 球位表；循環已展開，不再乘 cycles。',D:'成功：原位續桿；失誤：立即結束本局。',E:'第一桿成功：原位打第二顆；清完才記一輪成功。任一桿失敗：結束本輪，下一輪重擺。'}[r.spec.flow.template]):'選擇內建 20 關，或貼上、匯入新版關卡 JSON。';
 $('history').innerHTML=r&&r.history.length?r.history.map(h=>`<div>第 ${h.attempt} 次 · 第 ${h.shot} 桿 · ${esc(h.ball)} 號 · ${h.success?'成功':'失敗'}</div>`).join(''):'尚未開始';
 if(!r){$('screen').innerHTML=`<label>內建題庫<select id="preset">${levels.map((l,i)=>`<option value="${i}" ${i===selected?'selected':''}>${l.number}. ${esc(l.spec.name)} · ${l.spec.flow.template}</option>`).join('')}</select></label><label class="file">匯入 JSON 檔案<input id="file" type="file" accept=".json,application/json"></label><label for="json">或貼上 JSON</label><textarea id="json" placeholder='{"format":"poolgress.coach-level","version":1,...}'>${esc(importText)}</textarea><p class="hint">可載入單關、JSON 陣列或含 levels 陣列的題庫。</p>`;
 $('preset').onchange=e=>selected=Number(e.target.value);$('json').oninput=e=>importText=e.target.value;$('file').onchange=async e=>{try{load(await e.target.files[0].text());lastError='';render()}catch(err){$('error').textContent=err.message}};
 button('載入選取關卡',()=>runtime=E.create(levels[selected].spec),true);button('載入貼上的 JSON',()=>load(importText));return;}
 const s=r.spec,t=s.flow.template;
 if(showGiveup){$('screen').innerHTML='<h3>要放棄遊戲嗎？</h3><p>放棄後回到模板與球桌標記；繼續玩會保留目前進度。</p>';button('繼續玩',()=>showGiveup=false,true);button('確定放棄',()=>{showGiveup=false;runtime=E.create(s)});return;}
 if(r.phase==='template'){$('screen').innerHTML=table(r,true)+summary(s);button('模板載入完成・標記球位',()=>E.setup(r),true);}
 if(r.phase==='placement'){$('screen').innerHTML=table(r)+`<h3>請把球放在圈圈中</h3><p>${r.active.map(b=>`${esc(b.id==='cue'?'母球':b.id+' 號球')} (${b.x.toFixed(2)}, ${b.y.toFixed(2)})`).join(' · ')}</p>${s.setup.cuePlacement==='free'?'<p>開局母球為自由球；請選擇起點。</p><div class="coordinates"><label>母球 X<input id="freeX" type="number" min="0" max="8" step=".1" value="4"></label><label>母球 Y<input id="freeY" type="number" min="0" max="4" step=".1" value="3"></label></div>':''}`;button('球已擺好・開始擊球',()=>{if(s.setup.cuePlacement==='free'){const x=Number($('freeX').value),y=Number($('freeY').value);if(x<0||x>8||y<0||y>4)throw Error('母球需在球桌範圍內。');r.active.push({id:'cue',x,y,key:999});}r.phase='ready'},true);}
 if(r.phase==='ready'){$('screen').innerHTML=table(r)+`<h3>開始擊球</h3><p>本桿目標：${esc(E.target(r).id)} 號球</p>`+ruleText(E.rules(r).object,'子球')+ruleText(E.rules(r).cue,'母球');if(s.objectRules.order!=='ascending'&&r.active.filter(b=>b.id!=='cue').length>1){$('screen').insertAdjacentHTML('beforeend',`<label>選擇本桿目標球<select id="shotTarget">${r.active.filter(b=>b.id!=='cue').map(b=>`<option value="${b.key}" ${b.key===r.targetKey?'selected':''}>${esc(b.id)} 號球</option>`).join('')}</select></label>`);$('shotTarget').onchange=e=>{r.targetKey=Number(e.target.value);render()};}button('模擬擊球瞬間',()=>r.phase='moving',true);}
 if(r.phase==='moving'){$('screen').innerHTML=table({...r,active:[]})+'<h3>球體移動中</h3><p>擊球後清除球位提示，保留目標；等待所有球停止再判定。</p>';button('球已停止・進入判定',()=>r.phase='judging',true);}
 if(r.phase==='judging'){const q=E.rules(r),cue=r.active.find(b=>b.id==='cue');$('screen').innerHTML='<p>請依實際觀測勾選。未達標的條件保持未勾選。</p>'+ruleText(q.object,'子球')+'<label><input type="checkbox" id="objOK">子球終點符合上述規則</label>'+ruleText(q.cue,'母球')+(q.cue.target==='none'?'':`<label><input type="checkbox" id="cueOK">母球終點符合上述規則</label>${q.cue.target==='pocket_or_zone'?'<label><input type="checkbox" id="cueZone" checked>母球以停球區達標（會核對座標）</label>':''}<div class="coordinates"><label>母球停球 X<input id="cueX" type="number" step=".05" min="0" max="8" value="${cue?.x??4}"></label><label>母球停球 Y<input id="cueY" type="number" step=".05" min="0" max="4" value="${cue?.y??2}"></label></div>`)+[...q.object.lineRequirement.lineIndexes,...q.cue.lineRequirement.lineIndexes].map(i=>`<label><input type="checkbox" class="lineOK" value="${i}">${s.diagram.lines[i].side==='cue'?'母球':'目標子球'}本桿已碰線段 ${i+1}</label>`).join('')+(s.objectRules.order==='ascending'?'<label><input type="checkbox" id="orderOK" checked>首先接觸正確號碼球</label>':'')+`<label><input type="checkbox" id="foul">${s.fouls?.otherObjectBallsMustNotMove?'其他子球被碰動／':''}${s.fouls?.multipleObjectPotsForbidden?'一桿進多顆／':''}其他違規</label><label><input type="checkbox" id="unknown">觀測證據不足，需要覆核</label><p class="hint">續桿會保留母球停球座標。球路不會自動判為成功。</p>`;
 button('提交本桿判定',()=>E.judge(r,{object:$('objOK').checked,cue:$('cueOK')?.checked,cueInZone:$('cueZone')?.checked,cueX:Number($('cueX')?.value),cueY:Number($('cueY')?.value),lines:[...document.querySelectorAll('.lineOK:checked')].map(n=>Number(n.value)),order:$('orderOK')?.checked,foul:$('foul').checked,unknown:$('unknown').checked}),true);if(r.last?.startsWith('證據'))$('screen').insertAdjacentHTML('beforeend',`<p role="status">${esc(r.last)}</p>`);}
 if(['result','continuation'].includes(r.phase)){$('screen').innerHTML=table(r)+`<h3>${esc(r.last)}</h3><p>${r.phase==='continuation'?(t==='A'?'剩餘子球保持原位，直接擊打下一個號碼，不需重擺。':'保持母球與剩餘球的現況，繼續下一桿。'):'本次已結束，下一次依設定重擺。'}</p>`;button(r.phase==='continuation'?'原位續桿':'擺下一次的球',()=>r.phase==='continuation'?r.phase='ready':E.setup(r),true);}
 if(r.phase==='settlement'){const result=E.result(r);$('screen').innerHTML=`<div class="stars">${'★'.repeat(result.stars)}${'☆'.repeat(3-result.stars)}</div><h3>${result.passed?'挑戰過關':'再接再厲'}</h3><div class="score">${r.score} <small>/ ${s.scoring.total}</small></div><p>${s.scoring.unit==='cleared_rounds'?'完整清檯輪數':s.scoring.unit==='balls'?'成功進球數':'成功次數'} · 過關門檻 ${s.scoring.pass}</p>`;button('再挑戰一次',()=>{runtime=E.create(s);runtime.phase='template'},true);if(!embedded)button('選擇其他關卡',()=>runtime=null);}
 if(!['description','location','settlement'].includes(r.phase)){button('關卡說明',()=>{$('help-content').innerHTML=summary(s)+ruleText(E.rules(r).object,'本桿子球')+ruleText(E.rules(r).cue,'本桿母球');$('help').showModal()});button('放棄本次遊戲',()=>showGiveup=true);}
}
const embedded=new URLSearchParams(location.search).get('embedded')==='1';
let embeddedSpec=null;
if(embedded){document.body.classList.add('embedded');
 new ResizeObserver(()=>parent.postMessage({type:'poolgress.workflow.height',height:document.querySelector('main').getBoundingClientRect().height},location.protocol==='file:'?'*':location.origin)).observe(document.querySelector('main'));
 window.addEventListener('message',e=>{if(e.source!==parent||e.origin!==location.origin||e.data?.type!=='poolgress.workflow.spec')return;
 showGiveup=false;lastError='';
 try{if(e.data.errors?.length)throw Error(e.data.errors.join('；'));runtime=E.create(e.data.spec);embeddedSpec=e.data.spec;render();}
 catch(err){runtime=null;embeddedSpec=null;lastError=err.message;render();$('screen').innerHTML='<h3>等待完成關卡設定</h3><p>請在上方工作台補齊球位、目標與計分規則，完成後流程會自動顯示。</p>';$('actions').replaceChildren();parent.postMessage({type:'poolgress.workflow.error',message:err.message},location.protocol==='file:'?'*':location.origin);}
 });
 parent.postMessage({type:'poolgress.workflow.ready'},location.protocol==='file:'?'*':location.origin);
}
$('reset').onclick=()=>{runtime=null;lastError='';showGiveup=false;render()};$('close-help').onclick=()=>$('help').close();render();
